### ISSUE TITLE
Snapping indicator wrong when route in between

### ISSUE THREAD

**Issue by daniel-j-h** [perliedman/leaflet-routing-machine#356] opened 2016-12-15 09:33 UTC
Example on the landing page:

![snap](https://cloud.githubusercontent.com/assets/527241/21218494/2d8babbc-c2b1-11e6-8d75-cee3b1cb84e4.png)

We can't snap to the island where the `A` marker is dropped at. The route starts north of Port Blair to the left of `A`. But the snapping indicator (the grey-ish line starting from `A`) ends at the ferry route in between. Instead it should fully extend to the route's actual starting point north of Port Blair.

If you move `A` around you will see that it always extends to the nearest route. Unless you want to hop on and off ferrys in the middle of the ocean, this is not optimal :)

cc @perliedman @mokob

**Comment by perliedman** [comment] 2016-12-15 09:54
Hi @daniel-j-h, very interesting, thanks for submitting this!

Looking at the code, I think this happens since LRM tries to figure out which coordinate in the route belongs to which waypoint by itself, instead of using this information as provided by OSRM (some other routing engines does not include this info, so it tries to handle this gracefully - this issue also clearly illustrates a case where that logic breaks down).

I will try to look at this tomorrow, unless someone beats me to it (help is, as always, greatly appreciated).

**Comment by perliedman** [comment] 2016-12-16 15:03
I've tracked this down and have a fix, the problem is, as stated above, that LRM did not use indices based on OSRM's response, but rather tried to figure them out from which coordinate in the route was closest to the waypoints, which doesn't work in this case.

However, I also figured out that there doesn't appear to be any direct mapping between the waypoints and their corresponding index in the route's geometry. That is, if I want to know which coordinate in the geometry that corresponds to a waypoint (except for first and last), this information can only be retrieved by looking at the route's steps.

This is a problem, since LRM fetches routes this way:

1. fetch simplified geometry first, with steps
2. on demand fetch detailed geometry without steps

For step 2, I now have to include steps as well, since there's otherwise no way to map waypoints to the new geometry (as I understand it). This is of course not good for performance, as much more data is transferred, and I would guess a lot more work is generated on the server.

I will push my fix for now, but any ideas for improvement from @daniel-j-h or other memebers of the OSRM team would be welcome!

**Closed** 2016-12-16 15:05 UTC

**Comment by daniel-j-h** [comment] 2016-12-19 10:51
The `Waypoint` object has a location attached to it:
http://project-osrm.org/docs/v5.5.1/api/#waypoint-object

and the `RouteStep`s `StepManauever` `type` will be `depart / arrive` at Waypoints:
http://project-osrm.org/docs/v5.5.1/api/#stepmaneuver-object

the `RouteStep` also contains the geometry:
http://project-osrm.org/docs/v5.5.1/api/#routestep-object

but you're right you need the detailed geometry then. cc @themarex @mokob
