### ISSUE TITLE
Hide instructions

### ISSUE THREAD

**Issue by kill-process** [perliedman/leaflet-routing-machine#544] opened 2019-09-02 13:36 UTC
How to hide the text instructions panel. Not the route line

**Comment by rkroelin** [comment] 2019-09-03 04:29
Stumbled on this looking for an answer to another question and happened to notice your question:

**Comment by perliedman** [comment] 2019-09-03 14:37
Yes, this is a duplicate of #20.

**Closed by perliedman** 2019-09-03 14:37 UTC
