### ISSUE TITLE
Problem with mapbox routing

### ISSUE THREAD

**Issue by norx85** [perliedman/leaflet-routing-machine#533] opened 2019-06-03 10:45 UTC
Hi @perliedman, i've found a very strange bug when i try to use mapbox routing (others routers seems to work).

As you can see in the screenshots, the route get placed as a line on top of the world map, but when i do a zoom-in it become correctly placed

![screenshot1](https://user-images.githubusercontent.com/1897765/58794843-74890b00-85f9-11e9-8ff9-740c205ee5c5.png)
![screenshot2](https://user-images.githubusercontent.com/1897765/58794844-74890b00-85f9-11e9-9e0e-917a793c1226.png)
![screenshot3](https://user-images.githubusercontent.com/1897765/58794845-74890b00-85f9-11e9-809a-cb10e42c64f6.png)

This is the code to reproduce:
```
function setupRouting() {
    mapboxRouting = L.Routing.mapbox(accessToken, { profile : 'mapbox/walking' });
    routing = L.Routing.control({
        router: mapboxRouting,
        waypoints: waypoints,
        lineOptions : {
            styles : [{color: 'black', opacity: 0.05, weight: 9}, {color: 'white', opacity: 0.8, weight: 6}, {color: '#398aca', opacity: 1, weight: 4}],
        },
        showAlternatives: false,
        createMarker : function(){ return null },
        routeWhileDragging: true,
        addWaypoints: true,
        draggableWaypoints: true,
    }).addTo(map);
}
```

I'm using:

- leaflet 1.5.1, but i tried to use older versions with no success (1.4.x, 1.3.x)
- leaflet-routing-machine 3.2.12

Thanks for your work

**Comment by perliedman** [comment] 2019-06-04 11:12
Hi,
I seem to remember someone else bringing up more or less the same issue on Gitter. The problem is that Mapbox changed their API for some reason, so that passing the parameter `overview=false` now gives the result you show.

We should investigate why this change was made and what the best fix is, but sadly I do not think I will have the time personally, it has been a long time since I actively used Leaflet Routing Machine myself.

**Comment by norx85** [comment] 2019-06-04 13:52
Ok, thanks for your reply.
I've succesfully made it working setting `autoRoute` to `false` and manually calling 'routing.route()' with `geometryOnly = true` and `simplifyGeometry = false`.

The code now looks like:
```
function setupRouting() {
    mapboxRouting = L.Routing.mapbox(accessToken, { profile : 'mapbox/walking' });
    routing = L.Routing.control({
        router: mapboxRouting,
        waypoints: waypoints,
        autoRoute : false,
        lineOptions : {
            styles : [{color: 'black', opacity: 0.05, weight: 9}, {color: 'white', opacity: 0.8, weight: 6}, {color: '#398aca', opacity: 1, weight: 4}],
        },
        showAlternatives: false,
        createMarker : function(){ return null },
        routeWhileDragging: true,
        addWaypoints: true,
        draggableWaypoints: true,
    }).addTo(map);

    routing.route({ geometryOnly : true, simplifyGeometry: false })
}
```

**Comment by maks-dwarf** [comment] 2019-06-07 14:35
After calling "routing.route({ geometryOnly : true, simplifyGeometry: false })" my "routesfound" event stopped working. I have used this event to calculate a distance on the route. So problem is that i could not pass both "options" and callback together. Besides "simplifyGeometry: false" does not exists in api.

I have fixed it by overring a little part of sourse code in my function. It of course have to be fixed in code, but have no idea how to do it.. here is my code..
`routing.route({
       geometryOnly: true,
        callback: routeFoundCallback
 });`

`routeFoundCallback: function (err, routes = []) {
        if (routes && routes.length > 0) {
            this._clearLines();
            this._clearAlts();
            routes.forEach(function(route, i) { route.routesIndex = i; });
            var selectedRoute = routes.splice(0,1)[0];
            this._routeSelected({route: selectedRoute, alternatives: routes});
            calculateRouteLength(selectedRoute); // inside can you calculate length.
        }
    },`

**Comment by josef-prantauer** [comment] 2019-06-13 12:24
i was facing the same problem. the cause for me was that the router sent an encoded geometry with a default precision of 5 whereas the server seemed to respond with an encoded geometry of precision 6.
setting
`polylinePrecision: 6`
in mapbox-router-constructor options resolved this problem for me.

**Comment by geografa** [comment] 2019-07-16 18:36
Mapbox did make updates to the walking profile to improve its precision so it now returns `polyline6` encoding. Would it be possible to add this as a parameter to [mapbox.js](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/mapbox.js) to avoid [the default](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/osrm-v1.js#L28) `polyline5`?

**Comment by perliedman** [comment] 2019-07-17 08:41
@geografa they made that change without bumping the API version? That sounds very weird, since it must break any existing implementations, if I understand correctly.

**Comment by Batisska** [comment] 2019-07-21 22:15
> i was facing the same problem. the cause for me was that the router sent an encoded geometry with a default precision of 5 whereas the server seemed to respond with an encoded geometry of precision 6.
> setting
> `polylinePrecision: 6`
> in mapbox-router-constructor options resolved this problem for me.
> by this approach the 'routesfound' event was still fired
> 
> probably also because of this issue, when zooming closer to the resulting route, so that at least start or end marker is outside of the extent, it is required to prevent another routing request by
> `router.requiresMoreDetail = false`
> otherwise the dashed lines re-appear on screen..
> this is for sure more a hack than a solution but resolved the that issue for me.

Hey. Tell me how to set requiresMoreDetail to false. Do not use leaflet-routing-machine.js dist. Below is an example of my code.
```
           L.Routing.control({
                router: L.Routing.mapbox(this.token,{
                    profile : 'mapbox/walking',
                    language: 'ru',
                    polylinePrecision: 6,
                }),
                waypoints: [
                    L.latLng(67.68018769358207,33.24469327184678),
                    L.latLng(67.69174406398201,33.43757738917143)
                ],
            }).addTo(this.$refs.myMap.mapObject);
```

**Comment by perliedman** [comment] 2019-07-22 06:39
@Batisska this should work:

```js
var NoExtraDetailRouter = L.Routing.Mapbox.extend({
    requiresMoreDetail: function() { return false; }
});

           L.Routing.control({
                router: new NoExtraDetailRouter(this.token,{
                    profile : 'mapbox/walking',
                    language: 'ru',
                    polylinePrecision: 6,
                }),
                waypoints: [
                    L.latLng(67.68018769358207,33.24469327184678),
                    L.latLng(67.69174406398201,33.43757738917143)
                ],
            }).addTo(this.$refs.myMap.mapObject);

**Comment by danpat** [comment] 2019-07-24 16:47
@perliedman Looks like this was a missing test case in our coverage - we rolled out some changes and this has indeed broken backward compat.

Working on a fix on our end, I'll post an update here when it's deployed.  Apologies to folks who hit this.

**Comment by josef-prantauer** [comment] 2019-08-01 15:23
seems walking-precision is back to 5 again.
@danpat is it possible the server sends the encoding precision in the directions api in the response?
this way clients could dynamically handle whatever precision is used.

**Comment by danpat** [comment] 2019-08-01 15:31
@josef-prantauer you noticed fast, we only *just* deployed that, I hadn't even got around to posting a follow-up on this ticket yet.

We've considered it, but haven't thought it necessary - the API documentation describes what *should* occur based on the input parameters.  The way this bug played out, we likely would've said "this is a polyline5" but returned a polyline6, so I'm not sure it would've helped.

There's now a regression test in place (there was also one previously, but it was incorrect - who tests the tests?), so this particular issue shouldn't recur.

**Comment by perliedman** [comment] 2019-08-06 12:02
Thanks for the updates, @josef-prantauer and @danpat!

If I understand correctly, I can close this, since the issues should be fixed. If you still think this is an issue in Leaflet Routing Machine, just post a note and we'll see if we should re-open or just add a new issue.

**Closed by perliedman** 2019-08-06 12:02 UTC
