### ISSUE TITLE
Alternatives and routes count

### ISSUE THREAD

**Issue by sixertoy** [perliedman/leaflet-routing-machine#262] opened 2016-06-05 10:49 UTC
Hello :)

As i would like to use OSRM's Trip service + OSRM's Route service (because Trip is not exactly what i expect to have), i've decided to use the Route service combined to the Trip one.
So , i've set OSRM.route service `overview` options to `false`, do not need geometry.
I've get an Exception in `L.Routing.Control.route`method by `this.setAlternatives(routes);`

Perhaps alternatives routes no need to be parsed if there's only one route :)

[Edit]
OSRM's Route service do not seem to return any alternatives for
```javascript
waypoints = [
                new L.Routing.Waypoint(L.latLng(43.61092, 3.87723), 'Montpellier', opts),
                new L.Routing.Waypoint(L.latLng(44.8417, -0.5839), 'Bordeaux', opts),
                new L.Routing.Waypoint(L.latLng(48.4463, 1.4864), 'Chartres', opts),
                new L.Routing.Waypoint(L.latLng(48.6839, 6.1983), 'Nancy', opts),
                new L.Routing.Waypoint(L.latLng(48.85341, 2.34880), 'Paris', opts),
                new L.Routing.Waypoint(L.latLng(52.37403, 4.88969), 'Amsterdam', opts)
            ];
```

Of course, thanks for the 'leaflet-routing-machine' :)

**Comment by perliedman** [comment] 2016-06-08 06:43
Hi, `setAlternatives` is always used, even if there's only one altermative, so that is to be expected.

Hard to tell without seeing the exception or an example, but it sounds like the problem is that you're disabling the geometry. The control expects the returned route to contain a geometry.

**Comment by perliedman** [comment] 2016-06-10 12:39
Closing for now, please provide more info if you still think this is an issue.

**Closed by perliedman** 2016-06-10 12:39 UTC
