### ISSUE TITLE
On zoom, the map shows two routes instead of one

### ISSUE THREAD

**Issue by justmatt25** [perliedman/leaflet-routing-machine#458] opened 2018-02-09 18:42 UTC
I created a map and it shows one route as expected (see attached).
![image](https://user-images.githubusercontent.com/28732959/36043893-cf004faa-0d9e-11e8-8bd6-32d825466718.png)

When I zoom in and then zoom out again it then shows two routes (see attached).
![image](https://user-images.githubusercontent.com/28732959/36043955-05887548-0d9f-11e8-97f1-d444ae37f8c5.png)

**Comment by perliedman** [comment] 2018-02-12 08:16
It looks like the itinerary shows two alternatives already in the first screenshot, so the weird thing seems to be that both routes aren't shown there already. On the other hand, the styling for the alternative also looks weird.

Could you share some code that illustrates this issue?

**Comment by justmatt25** [comment] 2018-02-12 14:22
Hi @perliedman 
Thanks for the response! I am using Angular with typescript, here is the code:


```
        this.waypoints =[
            L.latLng(40.5663651,-75.6032277),
            L.latLng(42.3673945,-83.0750408),
          ]

        this.shipper1 = "40.5663651";
        this.shipper2 = "-75.6032277";
        this.receiver1 = "42.3673945";
        this.receiver2 = "-83.0750408";

      let map = new L.Map("map")

        let openmap = L.tileLayer("http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
            attribution: 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> ',
            fileSelectedRoutes:"false"
          }).addTo(map);
       
           this.route = L.Routing.control({
            waypoints: this.waypoints,
            createMarker: function() { return null; }
          }).addTo(map);

        L.marker([this.shipper1,this.shipper2]).addTo(map);
        L.marker([this.receiver1,this.receiver2]).addTo(map);

        let popup = L.popup();
    
        function onMapClick(e) {
            
          popup
          .setLatLng(e.latlng)
          .setContent("You clicked the map at " + e.latlng.toString())
          .openOn(map);
        }
        map.on('click', onMapClick);
```

**Comment by Brandhor** [comment] 2018-02-15 18:08
this is a duplicate of #319 
I've created a basic example to show this issue https://jsfiddle.net/4j7050te/1/
is it possible to auto select the first route instead of showing both of them?

**Closed** 2018-02-16 09:55 UTC
