### ISSUE TITLE
React Component

### ISSUE THREAD

**Issue by kraegpoeth** [perliedman/leaflet-routing-machine#400] opened 2017-03-14 09:53 UTC
I am quite new to react but have really tried to implement this as a custom component in react but just cant get it to work. Posting here in order to hopefully get some help.

Here is what I have so far:
Routing.jsx
```
import {MapLayer} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet-routing-machine';

export default class RoutingMachine extends MapLayer {
    createLeafletElement (props: Object): Object {
      const {map, from, to} = this.props
      return L.Routing.control({
        position: 'topleft',
        waypoints: [
          L.latLng(from[0], from[1]),
          L.latLng(to[0], to[1]),
        ],
      });
    }
}
```

and Directions.jsx

```
import React, { Component } from 'react';
import { Map, Marker, Circle, TileLayer } from 'react-leaflet';
import RoutingMachine from './Routing.jsx';

export default class Directions extends Component {

  render() {
    const position = [this.props.latLng.lat, this.props.latLng.lng]

    return(

          <div className="directions">
            <Map
              animate={true}
              center={position}
              /*zoom={this.props.zoom}*/
              onZoomEnd={this.updateZoom}
              onClick={this.updatePosition}
              ref='map'>
              <TileLayer
                attribution='&copy <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
                url='http://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png'
              />
              <RoutingMachine from={position} to={this.props.venue.location.coordinates} map={this.refs.map}/>
              <Marker
                position={position}
                ref='marker'
              />
            </Map>
          </div>
    )
  }
}
```

Right now the map is not loading, but i get his in the console: 
> "You are using OSRM's demo server. Please note that it is *NOT SUITABLE FOR PRODUCTION USE*....." 

So it seems that there is some connection to the routing-machine api and i also get this in the console:
> "Routing error: Object {status: -3, message: "TypeError: Cannot read property 'appendChild' of undefined"}"

Sorry for the newbie question but really like the react leaflet package and think it would be a huge benefit to have a react-leaflet-routing-machine package on npm. Thanks.

**Comment by perliedman** [comment] 2017-04-27 09:54
Hi there,
and sorry for a late reply.

Unfortunately, I don't have enough experience with react-leaflet to be able to help you with this.

From the error message, it sounds like the control is attempting to create the itinerary, but for some reason the control's DOM container elements haven't been created, but that is just a guess. From your code, I don't see the control being added to the map anywhere, might that be the problem?

**Comment by Eugene-Sviridov** [comment] 2017-12-20 09:17
@kraegpoeth Hi. Try to return this.
```
L.Routing.control({
      waypoints: [
        L.latLng(from.latitude, from.longitude),
        L.latLng(to.latitude, to.longitude),
      ],
}).addTo(map)._plan;
```

**Comment by perliedman** [comment] 2017-12-20 09:31
Closing this since it doesn't look like there's something we can do on the LRM side of this.

**Closed by perliedman** 2017-12-20 09:31 UTC

**Comment by Eugene-Sviridov** [comment] 2017-12-20 09:59
Sorry. I just want to add a few notes.
There is a method .getPlan(), so you should use it instead of ._plan.
Also if somebody want to change default settings you should put it in object
```
let leafletElement = L.Routing.control({
      waypoints: [
        L.latLng(from.latitude, from.longitude),
        L.latLng(to.latitude, to.longitude),
      ],
      lineOptions: {
        styles: [{ color: '#000', opacity: 0.8, weight: 6 }]
      },
      addWaypoints: false,
      draggableWaypoints: false,
    })
    .addTo(map);

return leafletElement.getPlan();
```

**Comment by chiragpoddar12** [comment] 2018-10-30 23:12
I am having a problem getting the component work. Was anyone successful after all?
```
<Map   center={mapCenter} zoom={this.state.zoom} ref='map'><TileLayer
                url='http://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png'/>
           
                  <Marker position={position}>
                  </Marker>
               
              <Routing from={[57.74, 11.94]} to={[57.6792, 11.949]} map={this.refs.map}/>
            </Map>
```
-------------------------------------------------------------------------------------
    createLeafletElement () {}
    componentWillMount(){
      const {map, from, to} = this.props;
      this.leafletElement = L.Routing.control({
      waypoints: [
        L.latLng(from[0], from[1]),
        L.latLng(to[0], to[1]),
      ],
      lineOptions: {
        styles: [{ color: '#000', opacity: 0.8, weight: 6 }]
      },
      addWaypoints: false,
      draggableWaypoints: false,
    })
    .addTo(map.leafletElement);

      return this.leafletElement.getPlan();
    }
}`



What is it i am doing wrong? I get the error **Uncaught TypeError: Cannot read property 'layerContainer' of undefined
    at RoutingMachine.get (MapLayer.js:77)
    at RoutingMachine.componentDidMount (MapLayer.js:38)**

**Comment by Eugene-Sviridov** [comment] 2018-10-30 23:39
@chiragpoddar12 try to move your code from ```componentWillMount``` to ```createLeafletElement```

You will have something like this

```
class RoutingMachine extends MapLayer {
  createLeafletElement() {
    const { color, map, road } = this.props;

    let leafletElement = L.Routing.control({
      waypoints: road,
      lineOptions: {
        styles: [{ 
          color, 
          opacity: .8,
          weight: 6 
        }]
      },
      addWaypoints: false,
      draggableWaypoints: false,
      fitSelectedRoutes: false,
      showAlternatives: false,
      altLineOptions: { styles: [{opacity: 0}] },
      createMarker: () => { return null; }
    })
    .addTo(map);

    return leafletElement.getPlan();
  }
}
```

**Comment by chiragpoddar12** [comment] 2018-10-31 00:00
@Eugene-Sviridov This does not help either. Still getting the same error

I just simply want to display some markers and path on the map. Not sure how to do this in React.

![image](https://user-images.githubusercontent.com/6632044/47757770-e550f900-dc9f-11e8-80c7-646c82425a8b.png)

**Comment by Eugene-Sviridov** [comment] 2018-10-31 00:09
@chiragpoddar12 Do you have a public repository so I can test it? If not:
1) Could you send source code of ```Routing``` component?
2) Check ```map``` variable in  ```Routing``` component. It should has ```leafletElement```

**Comment by chiragpoddar12** [comment] 2018-10-31 09:03
You can find the routing component below. I had to pass map.leafletElement to the addTo otherwise it was giving me the error of "map.getSize" not found


**Routing Component**
```
import {MapLayer} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet-routing-machine';

export default class RoutingMachine extends MapLayer {
  createLeafletElement() {
    const { color, map, road } = this.props;

    let leafletElement = L.Routing.control({
      waypoints: road,
      lineOptions: {
        styles: [{
          color,
          opacity: .8,
          weight: 6
        }]
      },
      addWaypoints: false,
      draggableWaypoints: false,
      fitSelectedRoutes: false,
      showAlternatives: false,
      altLineOptions: { styles: [{opacity: 0}] },
      createMarker: () => { return null; }
    })
    .addTo(map.leafletElement);

    return leafletElement.getPlan();
  }
}
```

Main Component (Containing Map)
```
<Map
    center={mapCenter}
    zoom={this.state.zoom}
    ref='map'>
    <TileLayer
        url='http://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png'/>
    <Marker position={position}>
    </Marker>
     <Routing from={[57.74, 11.94]} to={[57.6792, 11.949]} map={this.refs.map}/>
</Map>
```

**Comment by Eugene-Sviridov** [comment] 2018-10-31 09:22
@chiragpoddar12 I see only one difference in compare my implementation.

Try to change ```ref='map'``` to ```ref={this.saveMap}```
```
saveMap = (map: any) => {
        this.map = map;
        this.setState({
            isMapInit: true
        })
    }
```

Init ```Routing``` component when ```this.map``` is ready by

```{this.state.isMapInit && <Routing from={[57.74, 11.94]} to={[57.6792, 11.949]} map={this.map}/>```

**Comment by chiragpoddar12** [comment] 2018-10-31 09:34
Still the same issue persists. 
Am I using the correct libs?

import { Map, TileLayer, Marker } from 'react-leaflet';

**Comment by Eugene-Sviridov** [comment] 2018-10-31 10:28
@chiragpoddar12 Yes. 
You don't pass ```road``` props.

Could you send a screenshot of ```map``` and ```leafletElement```  in ```createLeafletElement``` in debugger?

**Comment by chiragpoddar12** [comment] 2018-10-31 18:22
**Routing Component**

![image](https://user-images.githubusercontent.com/6632044/47809900-dc146a80-dd39-11e8-9d8b-03dd26b55794.png)


**Map and Leaflet**
![image](https://user-images.githubusercontent.com/6632044/47809925-f0f0fe00-dd39-11e8-847f-bdf5f2a4268e.png)

Hope this helps :(

**Comment by Eugene-Sviridov** [comment] 2018-10-31 23:18
@chiragpoddar12 
The error is here
```this.context.layerContainer || this.context.map;```

If you check ```this``` in ```RoutingMachine``` component ```content``` will be undefined
<img width="538" alt="image" src="https://user-images.githubusercontent.com/17889108/47824095-4817c280-dd7c-11e8-90fa-6387c585785a.png">

Could you send source code of Main Component?

**Comment by chiragpoddar12** [comment] 2018-10-31 23:36
The Main component is a bit complicated for the actual use case. Following lines are related to the map
```
class MainNavBar extends React.Component {
  state = {
    positions:[
                [51.505,-0.09],
                [51.605,-0.19],
                [51.405,-0.09],
                [51.705,-0.19]
              ],
    permanentPositions:[
                [51.505,-0.09],
                [51.605,-0.19],
                [51.405,-0.09],
                [51.705,-0.19]
              ],
    selectedPosition:[],
    iconSize : [25, 35],
    isMapInit: false
  };
import { Map, TileLayer, Marker, Popup } from 'react-leaflet';
import L from 'leaflet';
   return(<Map
              center={mapCenter}
              zoom={this.state.zoom}
              className={classes.mapContainer}
              ref={this.saveMap}>
              <TileLayer
                url='http://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png'/>

              {positions.map((position, index) => {                                   //Putting more than one markers
                return (
                  <Marker position={position}
                          icon={(position[0] == selectedPosition[0] && position[1] == selectedPosition[1]) ? greyPin : bluePin}>
                  </Marker>
                );
              })}
            </Map>);
}
```

**Comment by Eugene-Sviridov** [comment] 2018-10-31 23:52
@chiragpoddar12 Did you check ```context```?

```return``` inside ```.map``` looks wrong. Just try to return this code for beginning

```
<Map bounds={[[-33.737269, 150.9391748], [-34.0110423, 151.4281265]]} ref={this.saveMap}>
              <TileLayer
                url='http://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png'/>
              {this.state.isMapInit && <Routing from={[57.74, 11.94]} to={[57.6792, 11.949]} map={this.map}/>}
</Map>
```

**Comment by chiragpoddar12** [comment] 2018-11-01 18:09
I am getting these following errors.
![image](https://user-images.githubusercontent.com/6632044/47870282-1e54af00-de01-11e8-9251-77690dff41f8.png)

**Comment by tommyspot** [comment] 2018-11-03 04:30
Hi, I got the same issue. Did anyone resolve this problem's @chiragpoddar12? Currently, I use:

"leaflet": "^1.3.3",
"leaflet-routing-machine": "^3.2.12",
"react-leaflet": "^2.0.0",

**Comment by tommyspot** [comment] 2018-11-03 16:56
Thanks, @Eugene-Sviridov, your example has worked well 👍 
[https://github.com/Eugene-Sviridov/leaflet_with_routing_sample](url)

This is a picture after I apply your code :)
<img width="734" alt="screen shot 2018-11-03 at 11 55 28 pm" src="https://user-images.githubusercontent.com/7645519/47955002-1a24bf00-dfc4-11e8-9ce5-1435d69137a2.png">

**Comment by slisystem** [comment] 2019-02-28 18:04
Hey @Eugene-Sviridov etc., I also have a quick question. I'm using react-leaflet as well and it works just fine thanks to your guidance here. I have my RoutingMachine:

`import { MapLayer } from 'react-leaflet';
import L from 'leaflet';
import { withLeaflet } from 'react-leaflet';
import 'leaflet-routing-machine/src';
import 'leaflet-routing-machine/dist/leaflet-routing-machine.css';

class RoutingMachine extends MapLayer {
  createLeafletElement() {
    const { color, map, road } = this.props;

    console.log("Route computation: ", road)

    let leafletElement = L.Routing.control({
      waypoints: road,
      router: L.Routing.mapbox('pk.eyJ1IjoiZGJvZ2RvbGwiLCJhIjoiY2pwY3JiamdrMzAzMjNwcGh4c2dkMTY0YyJ9.3orK4KP5OJIGN_nzs8buYQ'),
      lineOptions: {
        styles: [{ 
          color, 
          opacity: .8,
          weight: 6 
        }]
      },
      addWaypoints: true,
      draggableWaypoints: true,
      routeWhileDragging: false,
      fitSelectedRoutes: true,
      showAlternatives: false,
      altLineOptions: { styles: [{opacity: 1}] },
      //createMarker: () => { return null; }
    })
    .addTo(map.current.leafletElement);

    leafletElement.hide(); // hide road describtion
    console.log(leafletElement)
    return leafletElement.getPlan();
  }
}

export default withLeaflet(RoutingMachine);`

which is used here:

`            return (
                <Map
                    center={mapCenter}
                    zoom={zoomLevel}
                    ref={this.map}
                >
                    <Mapbox
                        accessToken={MAPBOX_ACCESS_TOKEN}
                    />
                    <RoutingMachine
                        color="#fff"
                        map={this.map}
                        //road={this.props.road}
                        road={this.state.stateRoute}
                    />
                </Map>
            );`

Now everything gets displayed beautifully, but after the user has finished the route (adding waypoints etc. allowed), I need the final data of the route (waypoints and list of all coordinates). How do I access those?

**Comment by rufoot** [comment] 2019-04-09 16:14
Hi @Eugene-Sviridov @tommyspot 
I have just checked the [https://github.com/Eugene-Sviridov/leaflet_with_routing_sample](url). And I applied it on my local.

Then I have got some issues as follows:
![Screen Shot 2019-04-09 at 7 13 32 PM](https://user-images.githubusercontent.com/43410634/55816708-9f744880-5afb-11e9-9e5b-e5b6537dc5cf.png)

Do you have any ideas to fix it?

**Comment by Eugene-Sviridov** [comment] 2019-04-09 16:20
@rufoot Hi. I saw the same error quite often. Unfortunately I don't know how OSRM demo server work and why it's unavailable sometimes. It's not a solution but try to refresh the page a couple of times. 

I believe the warning message in your screenshot is an answer.

**Comment by rufoot** [comment] 2019-04-09 22:56
I found a solution that can fix it.
We can use `L.Routing.osrmv1` for change server that paid or custom installed.
[http://www.liedman.net/leaflet-routing-machine/api/#l-routing-osrmv1](url)

I think it would be helpful for this issue.

**Comment by arjunghimire** [comment] 2019-05-10 05:03
I found a solution. Here is a working repo for implementation of  leaflet-routing-machine
https://github.com/arjunghimire/react-leaflet-routing-machine-example.

If you got any issues. Please let me know.

**Comment by kevinzhu** [comment] 2019-05-13 13:31
@Eugene-Sviridov , and etc. Your example in Github works pretty well in React. However, I am new in React and have an issues to customize the Marker of waypoints. As I would like the waypoints draggble in route, the Marker in Map.jsx may not suite. I tried to do the following in RoutingMachine.jsx (I simplified the logic and try to make the syntax work first ):

// createMarker: () => { return null; }
    createMarker: () => { console.log("Inside createMarker ..."); return <Marker icon={this.defaultIcon} position={L.latLng(57.74, 11.94)}></Marker>; }
 
But, got errors below.  I have not found an example of using createMarker inside RoutingMachine.jsx yet, e.g. @tommyspot or arjunghimire's. Appreciate any help! 

TypeError: m.addTo is not a function
NewClass._updateMarkers
http://localhost:3000/static/js/0.chunk.js:6907:15
  6904 | m = this.options.createMarker(i, this._waypoints[i], this._waypoints.length);
  6905 | 
  6906 | if (m) {
> 6907 |   m.addTo(this._map);
       |     ^  6908 | 
  6909 |   if (this.options.draggableWaypoints) {
  6910 |     this._hookWaypointEvents(m, i);

**Comment by arjunghimire** [comment] 2019-05-13 15:11
Hello

You can go through this doc (
http://www.liedman.net/leaflet-routing-machine/api/). I am currently busy
on projects.

**Comment by arjunghimire** [comment] 2019-05-14 03:51
Have you solved this problem?

**Comment by arjunghimire** [comment] 2019-05-14 03:59
https://gist.github.com/arjunghimire/82641d7e30ec990432510878d1974a93

Here is gist, where I solve your problem.

**Comment by arjunghimire** [comment] 2019-05-14 04:02
> @Eugene-Sviridov , and etc. Your example in Github works pretty well in React. However, I am new in React and have an issues to customize the Marker of waypoints. As I would like the waypoints draggble in route, the Marker in Map.jsx may not suite. I tried to do the following in RoutingMachine.jsx (I simplified the logic and try to make the syntax work first ):
> 
> // createMarker: () => { return null; }
> createMarker: () => { console.log("Inside createMarker ..."); return <Marker icon={this.defaultIcon} position={L.latLng(57.74, 11.94)}>; }
> 
> But, got errors below. I have not found an example of using createMarker inside RoutingMachine.jsx yet, e.g. @tommyspot or arjunghimire's. Appreciate any help!
> 
> TypeError: m.addTo is not a function
> NewClass._updateMarkers
> http://localhost:3000/static/js/0.chunk.js:6907:15
> 6904 | m = this.options.createMarker(i, this._waypoints[i], this._waypoints.length);
> 6905 |
> 6906 | if (m) {
> 
> > 6907 |   m.addTo(this._map);
> > |     ^  6908 |
> > 6909 |   if (this.options.draggableWaypoints) {
> > 6910 |     this._hookWaypointEvents(m, i);

Check this gist 
https://gist.github.com/arjunghimire/82641d7e30ec990432510878d1974a93

**Comment by kevinzhu** [comment] 2019-05-14 13:15
Here is a solution implemented by @arjunghimire - https://gist.github.com/arjunghimire/82641d7e30ec990432510878d1974a93. I tried to use his Routing module to replace the RoutingMachine module by @Eugene-Sviridov and got some error messages. But, it works pretty well after I make the following changes. Really appreciate your help! As the issue is closed, I should have raised the question separately in other forks.

-    .addTo(map.leafletElement);
+    .addTo(map.current.leafletElement);

**Comment by kirantpatil** [comment] 2019-08-06 12:01
Hello, 

May I know, Is there any port of it to react-native ?

If not then how to build one for react-native ?

Thanks.

**Comment by kirantpatil** [comment] 2019-08-06 17:01
Hi,

Thanks a lot. I will try it.

Regards,
Koran.

**Comment by tabakowy** [comment] 2020-05-12 09:07
Hey. Is there a way to clean up on componentWillUnmount()? I've tried everything and only `this.leafletElement.spliceWaypoints(0, 2)` works, but leaves some mess (empty panels and class instance). Perfect solution would be to make use of render() method instead of leaflet's addTo(). Any ideas?

```componentWillUnmount() {
  this.leafletElement.spliceWaypoints(0, 2)
  this.props.map.current.leafletElement.removeControl(this.leafletElement)
  this.props.leaflet.layerContainer.removeControl(this.leafletElement)
  this.props.leaflet.map.removeControl(this.leafletElement)
}```

**Comment by perliedman** [comment] 2020-05-15 12:58
@tabakowy Just removing the control from the `Map` instance with `removeControl` should be enough.

**Comment by tabakowy** [comment] 2020-05-15 13:56
@perliedman well, neither `this.props.map.current.leafletElement.removeControl(this.leafletElement)` nor `this.props.leaflet.layerContainer.removeControl(this.leafletElement)` is working :(

**Comment by perliedman** [comment] 2020-05-16 12:09
@tabakowy I don't know anything about react-leaflet, but it looks like your trying to remove the control from the wrong place. It should be from the Leaflet `L.Map` instance, not from an element or a layer container, whatever that is.

**Comment by sarahberraadi** [comment] 2020-05-23 03:35
@arjunghimire I use your example react leaflet routing machine but routing machine not work 
it only displays the map
![a](https://user-images.githubusercontent.com/65799229/82720753-12ac3000-9ca6-11ea-965d-21c4d8e967fd.png)
