### ISSUE TITLE
no route is visible 

### ISSUE THREAD

**Issue by tvjmohan** [perliedman/leaflet-routing-machine#359] opened 2016-12-25 10:13 UTC
Calculating the route caused an error. Technical description follows:
HTTP request failed: [object ProgressEvent]

it was working 6 months back. but now it is not showing any route.

![image](https://cloud.githubusercontent.com/assets/414051/21470666/da9b131a-cab8-11e6-8846-c684cfbf187c.png)

**Comment by perliedman** [comment] 2016-12-26 18:44
Are you using 6 months old code, or have you upgraded the plugin?

OSRM's demo server stopped supporting the old OSRM v4 API, so this might be the cause. Upgrade to the latest version of LRM, in that case.

**Comment by perliedman** [comment] 2017-01-06 17:02
Closing since no new info has been added.

**Closed by perliedman** 2017-01-06 17:02 UTC
