### ISSUE TITLE
Access-Control-Allow-Origin problem

### ISSUE THREAD

**Issue by PeterN-github** [perliedman/leaflet-routing-machine#318] opened 2016-09-30 13:40 UTC
Hi, I got following error when requesting a route from the OSRM Demo server:

XMLHttpRequest cannot load https://router.project-osrm.org/route/v1/driving/14.866411990971725,56.164197358231924;14.150390625,56.038294599616435?overview=false&alternatives=true&steps=true&hints=;. Origin http://localhost:8888 is not allowed by Access-Control-Allow-Origin.

I'm using Leaflet v0.0.7 and Leaflet-routing-machine v3.1.2.
Everything worked worked perfectly until today. Maybe OSRM API/implementation has changed?

**Comment by holek10** [comment] 2016-09-30 14:16
I've encountered the same problem.
Any solution ?

**Comment by holimatic** [comment] 2016-09-30 15:21
Since a few hour I'v the same problem!

**Comment by perliedman** [comment] 2016-10-03 05:56
Duplicate of #291 and #294.

The OSRM demo server is down, unfortunately not something LRM can do anything about. Set up your own OSRM server or use a paid service (or wait until the demo server comes back up).

**Closed by perliedman** 2016-10-03 05:56 UTC

**Comment by perliedman** [comment] 2016-10-03 05:58
Duplicate of #291 and #294.

The demo server is down, and there's unfortunately nothing LRM can do about it. Use your own OSRM server, use a paid service like Mapbox, or wait until the server comes back up.
