### ISSUE TITLE
Sometimes no route is calculated

### ISSUE THREAD

**Issue by CoughSyrup123** [perliedman/leaflet-routing-machine#488] opened 2018-09-14 09:07 UTC
Hi there,

I have a problem with calculating a route. Sometimes no route is calculated. I have no way of reproducing that and it doesn't happen every time.

My code how i calculate the route with two waypoints:

```javascript
function StartRouting(SWLat,SWLng,NELat,NELng){
  L.Routing.control({
    waypoints: [
      [SWLat,SWLng],
      [NELat,NELng]
    ],
    createMarker: function() { return null; },
    addWaypoints: false,
    show: false,
    draggableWaypoints: false,
    lineOptions: {
      styles: [
        {color: 'black', opacity: 0, weight: 0},
        {color: 'white', opacity: 0, weight: 0},
        {color: 'gray',  opacity: 1, weight: 2}
      ]
    },
    geocoder: L.Control.Geocoder.nominatim(),
  }).addTo(map);
}
```

**Comment by CoughSyrup123** [comment] 2018-09-14 10:42
I have integrated the error display and now get this message sometimes:
![2018-09-14 12_39_05-_ctel200f](https://user-images.githubusercontent.com/43266622/45545829-b0860100-b81b-11e8-8dd1-0bb5f9c061a5.png)

**Comment by perliedman** [comment] 2018-09-17 08:51
Hi!

It is most likely that the issue is OSRM's demo server, which suffers from a lot of load issues and quite frequently (IMHO) responds with HTTP 429 error codes, which prevents Leaflet Routing Machine from displaying a route.

So, if you need better availability, you need to either use a paid service provider (Mapbox is good and works well with Leaflet Routing Machine, but there are multiple other as well), or set up your own routing server.

I am closing this issue, since it is outside the scope of Leaflet Routing Machine to address this.

**Closed by perliedman** 2018-09-17 08:51 UTC
