### ISSUE TITLE
Leaflet routing machine/OSRM API are down

### ISSUE THREAD

**Issue by SamSalman** [perliedman/leaflet-routing-machine#194] opened 2016-01-11 14:09 UTC
Hello,

Its more than 6 hours Leaflet routing machine/OSRM API are down. It even doesn't work in Leaflet routing machine home page (http://www.liedman.net/leaflet-routing-machine/) and gives following console error:
XMLHttpRequest cannot load http://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=48.8588,2.3469&loc=52.3546,4.9039. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.liedman.net' is therefore not allowed access.

Why does it happen and is there any way to avoid said issue.

Thank you,

Regards,

Sam

**Comment by perliedman** [comment] 2016-01-11 14:19
@SamSalman Sorry, this is a known problem with the OSRM demo server: https://github.com/Project-OSRM/osrm-backend/issues/1873 at the moment.

Nothing I can do about it, we will have to wait it out until the OSRM team can fix it.

Having said that, I hope you are not relying on the demo server for anything crucial, it's just a demo with no guarantees. You should set up your own instance, or a service provider like Mapzen or Mapbox if you don't want to do it yourself.

Closing this; also duplicate of #193.

**Closed by perliedman** 2016-01-11 14:19 UTC
