### ISSUE TITLE
Routes lines are grey are always running through a specific point in California

### ISSUE THREAD

**Issue by seancdavis** [perliedman/leaflet-routing-machine#341] opened 2016-10-28 18:06 UTC
No matter which waypoints are given, each step goes through this specific point in California. And I'm not sure if it's related, but the styles don't seem to be sticking, either—it's always the same dashed grey line. Here are a couple screenshots from your demo:

![screen shot 2016-10-28 at 2 03 58 pm](https://cloud.githubusercontent.com/assets/5245089/19817006/b1ad0cd4-9d17-11e6-8540-5e89dd9c840f.png)

![screen shot 2016-10-28 at 2 03 15 pm](https://cloud.githubusercontent.com/assets/5245089/19817011/b5f1b2d6-9d17-11e6-890b-d31102e7b82a.png)

**Comment by Fulminant** [comment] 2016-10-28 21:10
+1

**Comment by perliedman** [comment] 2016-10-29 15:19
Duplicate of #337 and #340.

This is because OSRM's demo server is currently broken. It is a known problem, the OSRM team is sorting it out. It's not related to Leaflet Routing Machine itself.

The demo server is free, but comes without SLA or warranties. It often works, but sometimes it doesn't.

If you need better uptime, I suggest paying for a service provider (Mapbox's directions API is built on OSRM and works with LRM out of the box), or setting up your own server, which isn't that hard or expensive if you don't need global coverage.

**Closed by perliedman** 2016-10-29 15:19 UTC
